# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 20:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import backend.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('btc', 'Bitcoin'), ('csh', 'Cash'), ('cdt', 'Credit Card'), ('dbt', 'Debit Card'), ('gnc', 'Other')], default='gnc', max_length=3)),
                ('data', models.TextField()),
                ('encrypted', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(blank=True, null=True)),
                ('signature_required', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledgment_required', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(db_index=True, default=backend.api.models.Token.make_key, max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offer', models.DecimalField(decimal_places=2, max_digits=11)),
                ('offer_currency', models.CharField(default='USD', max_length=3)),
                ('completed', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_trans_buyer', to=settings.AUTH_USER_MODEL)),
                ('buyer_payment_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_trans_buyer_pd', to='api.PaymentData')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_trans_seller', to=settings.AUTH_USER_MODEL)),
                ('seller_payment_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_trans_seller_pd', to='api.PaymentData')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='signature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_req_sig', to='api.Signature'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_req_transaction', to='api.Transaction'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_req_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
