# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-01 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
