# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-14 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='error',
            field=models.TextField(null=True),
        ),
    ]
