# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-07 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='user',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Signature',
        ),
    ]
