# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-07 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180207_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='completed',
        ),
    ]
