# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-07 22:24
from __future__ import unicode_literals

import backend.api.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_remove_transaction_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('private_key', backend.api.fields.WIFPrivateKeyField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='paymentdata',
            name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='offer',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buyer_payment_data',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='offer_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller_payment_data',
        ),
        migrations.AddField(
            model_name='transaction',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PaymentData',
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_trans_buyer_wallet', to='api.Wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_trans_seller_wallet', to='api.Wallet'),
        ),
    ]
