# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-10 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180207_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='acknowledgment_required',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='signature_required',
        ),
    ]
