# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 23:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('btc', 'Bitcoin'), ('cdt', 'Credit Card'), ('dbt', 'Debit Card'), ('gnc', 'Other')], default='gnc', max_length=3)),
                ('data', models.TextField()),
                ('encrypted', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_witnesses', models.IntegerField(default=0)),
                ('offer', models.DecimalField(decimal_places=2, max_digits=11)),
                ('offer_currency', models.CharField(max_length=3)),
                ('date_proposed', models.DateTimeField(default=datetime.datetime(2017, 6, 5, 23, 31, 38, 14000, tzinfo=utc))),
                ('date_finalized', models.DateTimeField(null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_trans_buyer', to=settings.AUTH_USER_MODEL)),
                ('buyer_payment_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_trans_buyer_pd', to='api.PaymentData')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_trans_seller', to=settings.AUTH_USER_MODEL)),
                ('seller_payment_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_trans_seller_pd', to='api.PaymentData')),
            ],
        ),
        migrations.AddField(
            model_name='countersignature',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Transaction'),
        ),
        migrations.AddField(
            model_name='countersignature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
