# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170613_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_proposed',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date_finalized',
            new_name='finalized_at',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='offer_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
