// Wallets
export const LOAD_WALLETS_START = "LOAD_WALLETS_START";
export const LOAD_WALLETS_ABORT = "LOAD_WALLETS_ABORT";
export const LOAD_WALLETS_COMPLETE = "LOAD_WALLETS_COMPLETE";

// Users
export const LOAD_USER_START = "LOAD_PROFILE_USER_START";
export const LOAD_USER_ABORT = "LOAD_PROFILE_USER_ABORT";
export const LOAD_USER_COMPLETE = "LOAD_PROFILE_USER_COMPLETE";

// transactions
export const LOAD_TRANSACTIONS_START = "LOAD_PROFILE_TRANSACTIONS_START";
export const LOAD_TRANSACTIONS_ABORT = "LOAD_PROFILE_TRANSACTIONS_ABORT";
export const LOAD_TRANSACTIONS_COMPLETE = "LOAD_PROFILE_TRANSACTIONS_COMPLETE";

// requirements
export const LOAD_REQUIREMENTS_START = "LOAD_REQUIREMENTS_START";
export const LOAD_REQUIREMENTS_ABORT = "LOAD_REQUIREMENTS_ABORT";
export const LOAD_REQUIREMENTS_COMPLETE = "LOAD_REQUIREMENTS_COMPLETE";
