// Wallets
export const WALLETS_START_LOAD = "WALLETS_START_LOAD";
export const WALLETS_ABORT_LOAD = "WALLETS_ABORT_LOAD";
export const LOAD_WALLETS_COMPLETE = "LOAD_WALLETS_COMPLETE";
export const CREATE_WALLET_COMPLETE = "CREATE_WALLET_COMPLETE";
export const DELETE_WALLET_COMPLETE = "DELETE_WALLET_COMPLETE";

// Users
export const LOAD_USER_START = "LOAD_PROFILE_USER_START";
export const LOAD_USER_ABORT = "LOAD_PROFILE_USER_ABORT";
export const LOAD_USER_COMPLETE = "LOAD_PROFILE_USER_COMPLETE";

// transactions
export const LOAD_TRANSACTIONS_START = "LOAD_TRANSACTIONS_START";
export const LOAD_TRANSACTIONS_ABORT = "LOAD_TRANSACTIONS_ABORT";
export const LOAD_TRANSACTIONS_COMPLETE = "LOAD_TRANSACTIONS_COMPLETE";

// transactionCache
export const FETCH_TRANSACTION_START = "FETCH_TRANSACTION_START";
export const FETCH_TRANSACTION_ABORT = "FETCH_TRANSACTION_ABORT";
export const FETCH_TRANSACTION_COMPLETE = "FETCH_TRANSACTION_COMPLETE";

// requirements
export const REQUIREMENTS_START_LOAD = "REQUIREMENTS_START_LOAD";
export const REQUIREMENTS_ABORT_LOAD = "REQUIREMENTS_ABORT_LOAD";
export const LOAD_REQUIREMENTS_COMPLETE = "LOAD_REQUIREMENTS_COMPLETE";
export const SAVE_REQUIREMENT_COMPLETE = "SAVE_REQUIREMENT_COMPLETE";

// transactions-in-progress
export const TIP_REMOVE_REQUIREMENT = "TIP_REMOVE_REQUIREMENT";
export const TIP_UPDATE_REQUIREMENT = "TIP_UPDATE_REQUIREMENT";
export const TIP_UPDATE_PENDING_REQUIREMENT = "TIP_UPDATE_PENDING_REQUIREMENT";
export const TIP_PROMOTE_PENDING_REQUIREMENT = "TIP_PROMOTE_PENDING_REQUIREMENT";
export const TIP_REMOVE_PENDING_REQUIREMENT = "TIP_REMOVE_PENDING_REQUIREMENT";
export const TIP_UPDATE = "TIP_UPDATE";
export const TIP_DELETE = "TIP_DELETE";
